[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && gunicorn condominio.wsgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
