services:
  - type: web
    name: back-condominio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn condominio.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: condominio-db
          property: connectionString

databases:
  - name: condominio-db
    databaseName: condominio_rv3u
    user: condominio_rv3u_user
